name: AbyssMainPlugin
version: '1.0.0'
main: net.abyss.abyssmainplugin.AbyssMainPlugin
api-version: '1.20'

commands:
  generateGate:
    description: 게이트 생성
  destroyGate:
    description: 게이트 제거
  checkAllGate:
    description: 게이트 목록 확인
  openZombieGate:
    description: 좀비 게이트 시작